name: run-job

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Forrest Run!

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set Environment Variable
        env:
            MESSAGE: ${{ secrets.MESSAGE }}
        run: |
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install
      - name: Run JavaScript code
        run: npm run forrest 