name: run-job

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Forrest Run!
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        env:
          MESSAGE: ${{ secrets.MESSAGE }}
          # WEATHERKEY: ${{ secrets.WEATHERKEY }}
          # MONGOKEY: ${{ secrets.MONGOKEY }}
      - run: echo $MESSAGE
      - run: npm run forrest